### ISSUE TITLE
Default image when no dish image

### ISSUE THREAD

**Issue by sahilkalra16** [sahilkalra16/Grub#1]
Use default image when no image is present for a dish instead of using loaded.
Loaded will be displayed only when dish image is present and is being downloaded, which is working as expected.
![img_1145](https://cloud.githubusercontent.com/assets/935234/13194999/a4f2acfe-d7cb-11e5-9e36-dd7bca6252f2.PNG)

**Comment by tarunseera** [comment]
Done and also optimised image loading by cache
