### ISSUE TITLE
Wrong Category Visible

### ISSUE THREAD

**Issue by sahilkalra16** [sahilkalra16/Grub#10]
A wrong category is visible on a location where there are no veg dishes.
Steps to reproduce:
- Choose Area Chandni chowk
- Blank Veg Category is visible as there is only one non-veg dish for this area.
- This should be check for all categories by changing the category type of this dish.

change dish category using this url and test throughly http://203.145.168.17:8100/grub/dishes/form/312/129 
![img_1142](https://cloud.githubusercontent.com/assets/935234/13194992/569c6dc4-d7cb-11e5-9445-bc5efa71b4c7.PNG)

**Comment by tarunseera** [comment]
Done, but no dish found message will display and  if we don't want it it will take time to resolve

**Comment by sahilkalra16** [comment]
Re-opened...
Please Unit test before committing. 
![screen shot 2016-02-25 at 3 01 16 pm](https://cloud.githubusercontent.com/assets/935234/13315452/b9318a38-dbd0-11e5-89e8-5225d3065557.png)

**Comment by sahilkalra16** [comment]
@tarunseera have fixed this...focus on others
