### ISSUE TITLE
Wrong date in Activity View

### ISSUE THREAD

**Issue by sahilkalra16** [sahilkalra16/Grub#7]
Please make use of https://github.com/kevinlawler/NSDate-TimeAgo to change timestamp into relative dates.

**Comment by tarunseera** [comment]
Not help with given link i guess its coming wrong from server

**Comment by sahilkalra16** [comment]
{"activityId":99,"username":"10154363736559112","dishId":338,"timestamp":1456395579000,"dishName":"Butter Chicken","restaurantName":"Moti Mahal","restaurantId":131} 

timestamp 1456395579000 > http://www.epochconverter.com/ > to generate > 2/25/2016, 3:49:39 PM

Please look into it as online conversion is correct. the only i issue is see is that its may be 5:30 hrs back as server generated time respective to GMT and not GMT 5:30 which is used in India.

**Comment by tarunseera** [comment]
Done
